CLEAR SCREEN
SET SERVEROUTPUT ON
DECLARE
	N NUMBER;
BEGIN
	N := &RANDOM_NUMBER;
	IF ISARMSTRONG(N) THEN
		DBMS_OUTPUT.PUT_LINE(N||' IS AN ARMSTRONG NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(N||' IS NOT AN ARMSTRONG NUMBER');
	END IF;
END;
/