CLEAR SCREEN 
SET SERVEROUTPUT ON 
DECLARE
	V1 VARCHAR(10);
	V2 VARCHAR(10);
	V3 VARCHAR(10);
BEGIN
	V1 := 'TEAM';
	V2 := 'CRICKET';
	V3 := 'INDIA';
	DBMS_OUTPUT.PUT_LINE('BEFORE ANONYMOUS  : V1 = '||V1||', V2 = '||NVL(V2,'NULL')||' AND V3 = '||V3);
	TEST_PROC(V1,V2,V3);
	DBMS_OUTPUT.PUT_LINE('AFTER  ANONYMOUS  : V1 = '||V1||', V2 = '||NVL(V2,'NULL')||' AND V3 = '||V3);
	
END;
/	