SET SERVEROUTPUT ON;

DECLARE
    DNO  DEPARTMENTS.DEPARTMENT_ID%TYPE ;
    ENO  DEPARTMENTS.DEPARTMENT_ID%TYPE ;
    REC  DEPARTMENTS%ROWTYPE;

BEGIN
    DNO:= &DEPARTMENT_ID;
	ENO:= &MANAGER_ID;
	SELECT * INTO REC FROM DEPARTMENTS WHERE DEPARTMENT_ID = DNO AND MANAGER_ID = ENO;
    DBMS_OUTPUT.PUT_LINE('YES HE IS MANAGER');
    
EXCEPTION

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('INCORRECT INFORMATION');


END;
/

