CLEAR SCREEN 
SET SERVEROUTPUT ON 

CREATE OR REPLACE PROCEDURE SUMPROC(N1 IN NUMBER, N2 IN NUMBER) IS
	V1 NUMBER;
	V2 NUMBER;
	V3 NUMBER;
BEGIN
	V1 := N1;
	V2 := N2;
	V3 := N1+N2;
	DBMS_OUTPUT.PUT_LINE('SUM OF '||V1||' AND '||V2||' = '||V3);
END;
/	
