CLEAR SCREEN
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE CHECK_EMP(EID IN NUMBER,FLAG OUT BOOLEAN)IS
	V_ID EMPLOYEES.EMPLOYEE_ID%TYPE;

BEGIN

	SELECT EMPLOYEE_ID INTO V_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = EID;

	FLAG := TRUE;

EXCEPTION

	WHEN NO_DATA_FOUND THEN
		FLAG := FALSE;

END;
/