CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE  EMPLOYEES.EMPLOYEE_ID%TYPE;
    JTITLE JOBS.JOB_TITLE%TYPE;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT JOB_TITLE
    INTO JTITLE
    FROM JOBS
    WHERE JOB_ID = (
        SELECT JOB_ID
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = ECODE
    );

    IF UPPER(JTITLE) LIKE '%CLERK%' THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE IS A CLERK');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE IS NOT A CLERK');
    END IF;
END;
/
