CLEAR SCREEN 
SET SERVEROUTPUT ON;


DECLARE
    
    ENO  EMPLOYEES.EMPLOYEE_ID%TYPE;
    REC  EMPLOYEES%ROWTYPE;

BEGIN
    
	ENO:= &EMPLOYEE_ID;
	SELECT * INTO REC FROM EMPLOYEES WHERE EMPLOYEE_ID = TO_NUMBER(ENO);
	DBMS_OUTPUT.PUT_LINE('FIRST NAME :'||REC.FIRST_NAME);
    
EXCEPTION

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH EMPLOYEE PRESENT');
	WHEN OTHERS THEN
		    IF SQLCODE = -1722 THEN
				DBMS_OUTPUT.PUT_LINE(SQLCODE||':'||SUBSTR(SQLERRM,10));
			END IF;


END;
/
