CLEAR SCREEN
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE EMP_DETAILS(
	EID IN NUMBER
)
IS
	ENAME EMPLOYEES.FIRST_NAME%TYPE;
	ESAL EMPLOYEES.SALARY%TYPE;

	FLAG BOOLEAN;

BEGIN

	CHECK_EMP(EID,FLAG);

	IF FLAG THEN

		SELECT FIRST_NAME,SALARY
		INTO ENAME,ESAL
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID = EID;

		DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME = '||ENAME);
		DBMS_OUTPUT.PUT_LINE('SALARY = '||ESAL);

	ELSE

		DBMS_OUTPUT.PUT_LINE('EMPLOYEE NOT PRESENT');

	END IF;

END;
/