CLEAR SCREEN
SET SERVEROUTPUT ON 

DECLARE
    ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
    DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT D.DEPARTMENT_NAME
    INTO DNAME
    FROM EMPLOYEES E, DEPARTMENTS D
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.EMPLOYEE_ID = ECODE;

    DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME : ' || DNAME);
END;
/
