CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    TSAL  NUMBER;
BEGIN
    DNAME := '&DEPARTMENT_NAME';

    SELECT SUM(SALARY) INTO TSAL FROM EMPLOYEES E, DEPARTMENT D WHERE E.DEPARTMRNT_ID = D.DEPARTMENT_ID AND D.DEPARTMENT_NAME    = DNAME;
SELECT SUM(SALARY) INTO TSAL FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = DNAME);
    

    DBMS_OUTPUT.PUT_LINE('TOTAL SALARY : ' || TSAL);
END;
/
 