CLEAR SCREEN 
SET SERVEROUTPUT ON
DECLARE 
	ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
	FNAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
	ECODE:=&EMPLOYEE_ID;
	SELECT FIRST_NAME INTO FNAME FROM EMPLOYEES WHERE EMPLOYEE_ID=ECODE;
	DBMS_OUTPUT.PUT_LINE('FIRST NAME : '||FNAME);
END;
/