CLEAR SCREEN
SET SERVEROUTPUT ON
DECLARE
	NAME VARCHAR(20) ;
	AGE  NUMBER ;

BEGIN
	NAME := '&USER_NAME';
	AGE := &USER_AGE;
	DBMS_OUTPUT.PUT_LINE('NAME ENTERED : ' || NAME);
	DBMS_OUTPUT.PUT_LINE('AGE ENTERED : ' || AGE);

	
END;
/
