CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
	LID LOCATIONS.LOCATION_ID%TYPE;
	REC LOCATIONS%ROWTYPE;
BEGIN
	LID := '&LOCATION_ID';
	SELECT * INTO REC FROM LOCATIONS WHERE LOCATION_ID = LID; 
	DBMS_OUTPUT.PUT_LINE('LOCATION ID :' || REC.COUNTRY_ID);
	DBMS_OUTPUT.PUT_LINE('STREET ADDRESS :' || REC.STREET_ADDRESS);
	DBMS_OUTPUT.PUT_LINE('POSTAL CODE :' || REC.POSTAL_CODE);
	DBMS_OUTPUT.PUT_LINE('CITY NAME :' || REC.CITY);
END;
/
