CLEAR SCREEN
SET SERVEROUTPUT ON;

DECLARE
    
    ENO EMPLOYEES.EMPLOYEE_ID%TYPE;

    
    EREC EMPLOYEES%ROWTYPE;

BEGIN
    
    ENO := '&EMPLOYEE_ID';

    
    SELECT *INTO EREC FROM EMPLOYEES WHERE EMPLOYEE_ID = ENO;

    
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE DETAILS');
    DBMS_OUTPUT.PUT_LINE('---------------------------');
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID  : ' || EREC.EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('FIRST NAME   : ' || EREC.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('LAST NAME    : ' || EREC.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY       : ' || EREC.SALARY);
    DBMS_OUTPUT.PUT_LINE('DEPT ID      : ' || EREC.DEPARTMENT_ID);

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SUCH EMPLOYEE FOUND');

    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: INVALID EMPLOYEE ID (DATATYPE MISMATCH)');

    WHEN INVALID_NUMBER THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: INVALID NUMBER');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);

END;
/