CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    EID EMPLOYEES.EMPLOYEE_ID%TYPE := &EMPLOYEE_ID;
    SAL EMPLOYEES.SALARY%TYPE;
    AVG_SAL NUMBER;
    DNO EMPLOYEES.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT SALARY, DEPARTMENT_ID
    INTO SAL, DNO
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EID;

    SELECT AVG(SALARY)
    INTO AVG_SAL
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DNO;

    IF SAL < AVG_SAL THEN
        UPDATE EMPLOYEES
        SET SALARY = SALARY + (AVG_SAL - SALARY)
        WHERE EMPLOYEE_ID = EID;

        DBMS_OUTPUT.PUT_LINE('SALARY INCREASED');
    ELSE
        UPDATE EMPLOYEES
        SET SALARY = SALARY - (SALARY - AVG_SAL)
        WHERE DEPARTMENT_ID = DNO
        AND SALARY = (SELECT MIN(SALARY)
                      FROM EMPLOYEES
                      WHERE DEPARTMENT_ID = DNO);

        DBMS_OUTPUT.PUT_LINE('EXCESS ADJUSTED');
    END IF;

    DBMS_OUTPUT.PUT_LINE('Adjustment made successfully. Good bye');
END;
/
