CLEAR SCREEN
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE FACT_SERIES IS 
	N NUMBER;
	F NUMBER;
	S NUMBER;
	PROCEDURE FACT(X IN NUMBER, P OUT NUMBER) IS
	BEGIN
		P:=1;
		FOR I IN 1..X LOOP
			P:= P*I;
		END LOOP;
	END;
BEGIN
	N:=1;
	F:=0;
	S:=0;
	WHILE N<=10 LOOP
		FACT(N,F);
		S:= S+F;
		N:= N+2;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('SUM ='||S);
END;
/
