CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    DNO EMPLOYEES.DEPARTMENT_ID%TYPE := &DEPT_ID;
    TOTAL NUMBER := 0;
BEGIN
    FOR R IN (SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
              FROM EMPLOYEES
              WHERE DEPARTMENT_ID = DNO) LOOP

        DBMS_OUTPUT.PUT_LINE(
            R.EMPLOYEE_ID||' '||R.FIRST_NAME||' '||R.SALARY);

        TOTAL := TOTAL + R.SALARY;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('TOTAL SALARY : '||TOTAL);
END;
/
