CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
	ENO EMPLOYEES.EMPLOYEE_ID%TYPE;
	TYPE EMPRECORD IS RECORD
	(
		FNAME EMPLOYEES.FIRST_NAME%TYPE,
		LNAME EMPLOYEES.LAST_NAME%TYPE,
		SALARY EMPLOYEES.SALARY%TYPE,
		DPTNO EMPLOYEES.DEPARTMENT_ID%TYPE
	);
	REC EMPRECORD;
BEGIN
	ENO := &EMPLOYEE_ID;
	SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID INTO REC FROM EMPLOYEES WHERE EMPLOYEE_ID = ENO;
	DBMS_OUTPUT.PUT_LINE('FIRST NAME :' || REC.FNAME);
	DBMS_OUTPUT.PUT_LINE('LAST NAME :' || REC.LNAME);
	DBMS_OUTPUT.PUT_LINE('SALARY :' || REC.SALARY);
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID :' || REC.DPTNO);

END;
/
