CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
	CID COUNTRIES.COUNTRY_ID%TYPE;
	REC COUNTRIES%ROWTYPE;
BEGIN
	CID := '&COUNTRY_ID';
	SELECT * INTO REC FROM COUNTRIES WHERE COUNTRY_ID = CID; 
	DBMS_OUTPUT.PUT_LINE('COUNTRY ID :' || REC.COUNTRY_ID);
	DBMS_OUTPUT.PUT_LINE('COUNTRY NAME :' || REC.COUNTRY_NAME);
	DBMS_OUTPUT.PUT_LINE('REGION ID :' || REC.REGION_ID);
END;
/
