CLEAR SCREEN
SET SERVEROUTPUT ON;

DECLARE
    
    DNO DEPARTMENTS.DEPARTMENT_ID%TYPE;
    ENO DEPARTMENTS.MANAGER_ID%TYPE;

BEGIN

    
    DNO := '&DEPARTMENT_ID';
    ENO := '&EMPLOYEE_ID';

    
    SELECT MANAGER_ID INTO ENO FROM DEPARTMENTS WHERE DEPARTMENT_ID = DNO AND MANAGER_ID = ENO;

    DBMS_OUTPUT.PUT_LINE('YES, HE IS THE MANAGER OF THE DEPARTMENT');

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('INCORRECT INFORMATION SUBMITTED');

    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('INVALID DEPARTMENT ID OR EMPLOYEE ID');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OOPS! SOMETHING IS WRONG');

END;
/
