CLEAR SCREEN
SET SERVEROUTPUT ON;

DECLARE 
    DEPTNO NUMBER(7);
    TEMP   NUMBER(7);
    REC    DEPT%ROWTYPE;

BEGIN
    
    DEPTNO := TO_NUMBER('&DNO');
	REC.DNAME := '&DNAME';
    REC.LOC   := '&LOC';

    
    SELECT DNO 
    INTO TEMP 
    FROM DEPT 
    WHERE DNO = DEPTNO;
	

    
    DBMS_OUTPUT.PUT_LINE
    ('ERROR: DUPLICATE DEPARTMENT NUMBER NOT ALLOWED');
	

EXCEPTION

    
    WHEN NO_DATA_FOUND THEN
        REC.DNO   := DEPTNO;
        

        INSERT INTO DEPT VALUES REC;

        DBMS_OUTPUT.PUT_LINE('RECORD INSERTED SUCCESSFULLY');

    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: INVALID DEPARTMENT NUMBER');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SOMETHING IS WRONG');

END;
/