CLEAR SCREEN 
SET SERVEROUTPUT ON 

CREATE OR REPLACE PROCEDURE TEST_PROC(N1 IN VARCHAR, N2 OUT VARCHAR,N3 IN OUT VARCHAR) IS
	
BEGIN

	
DBMS_OUTPUT.PUT_LINE('BEFORE STORED  : N1 = '||N1||', N2 = '||NVL(N2,'NULL')||' AND N3 = '||N3);

  N3 := 'DHONI';

DBMS_OUTPUT.PUT_LINE('AFTER  STORED  : N1 = '||N1||', N2 = '||NVL(N2,'NULL')||' AND N3 = '||N3);




END;
/	
