CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE NUMBER;
    SAL   NUMBER;
    GRADE NUMBER;
BEGIN
    ECODE := &EMPLOYEE_ID;
    SELECT SALARY
    INTO SAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ECODE;

    
    SELECT GRADE
    INTO GRADE
    FROM SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL;

    
    IF GRADE = 3 THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE IS A GRADE 3 EMPLOYEE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE IS NOT A GRADE 3 EMPLOYEE');
    END IF;
END;
/
