CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    D1 DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    D2 DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    C1 NUMBER;
    C2 NUMBER;
    MAXSAL1 NUMBER;
    MAXSAL2 NUMBER;
    MINSAL1 NUMBER;
    MINSAL2 NUMBER;
    AVGSAL1 NUMBER;
    AVGSAL2 NUMBER;
    
BEGIN
    D1 := '&DEPT1';
    D2 := '&DEPT2';

    SELECT COUNT(*),MAX(SALARY) ,MIN(SALARY),AVG(SALARY) INTO C1,MAXSAL1,MINSAL1,AVGSAL1
      FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = D1);
SELECT COUNT(*),MAX(SALARY) ,MIN(SALARY),AVG(SALARY) INTO C2,MAXSAL2,MINSAL2,AVGSAL2
      FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = D2);





    DBMS_OUTPUT.PUT_LINE('EMPLOYEE DIFFERENCE : ' || ABS(C1 - C2));
DBMS_OUTPUT.PUT_LINE('MAXSAL DIFFERENCE : ' || ABS(MAXSAL1 - MAXSAL2));
DBMS_OUTPUT.PUT_LINE('MINSAL DIFFERENCE : ' || ABS(MINSAL1- MINSAL2));
DBMS_OUTPUT.PUT_LINE('AVGSAL DIFFERENCE : ' || ABS(AVGSAL1 - AVGSAL2));
END;
/
