CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
    MTH   NUMBER;
    YR    NUMBER;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT EXTRACT(MONTH FROM HIRE_DATE),
           EXTRACT(YEAR  FROM HIRE_DATE)
    INTO   MTH, YR
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ECODE;

    IF MTH = 2 AND YR = 1999 THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE WAS HIRED IN FEBRUARY 1999');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE WAS NOT HIRED IN FEBRUARY 1999');
    END IF;
END;
/
