CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
    DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT DEPARTMENT_NAME
    INTO DNAME
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = (
        SELECT DEPARTMENT_ID
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = ECODE
    );

    IF UPPER(DNAME) = 'PURCHASING' THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE WORKS IN PURCHASING DEPARTMENT');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE DOES NOT WORK IN PURCHASING DEPARTMENT');
    END IF;
END;
/
