CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
	ENO EMPLOYEES.EMPLOYEE_ID%TYPE;
	REC EMPLOYEES%ROWTYPE;
BEGIN
	ENO := &EMPLOYEE_ID;
	SELECT * INTO REC FROM EMPLOYEES WHERE EMPLOYEE_ID = ENO;
	DBMS_OUTPUT.PUT_LINE('FIRST NAME :' || REC.FIRST_NAME);
	DBMS_OUTPUT.PUT_LINE('LAST NAME :' || REC.LAST_NAME);
	DBMS_OUTPUT.PUT_LINE('SALARY :' || REC.SALARY);
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID :' || REC.DEPARTMENT_ID);

END;
/
