CLEAR SCREEN 
SET SERVEROUTPUT ON;


DECLARE
    USER_INVALID_NUMBER EXCEPTION;
	PRAGMA EXCEPTION_INIT(USER_INVALID_NUMBER, -6502);
    
    DREC  DEPT%ROWTYPE;

BEGIN
    
	DREC.ENO:= '&DEPARTMENT_NO';
	DREC.DNAME:= '&DEPARTMENT_NAME';
	DREC.LOC:= '&DEPARTMENT_LOCATION';
	INSERT INTO DEPT VALUES DREC;
	DBMS_OUTPUT.PUT_LINE('VALUE INSERTED SUCCESFULLY');
    
EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('DEPARTMENT NUMBER CANNOT BE DUPILCATED');
	WHEN USER_INVALID_NUMBER THEN
		DBMS_OUTPUT.PUT_LINE('INVALID DEPARTMENT NUMBER');
	WHEN OTHERS THAN
				DBMS_OUTPUT.PUT_LINE('OOPS! SOMETHING IS WRONG');
			END IF;


END;
/
