CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
	ENO EMPLOYEES.EMPLOYEE_ID%TYPE;
	TYPE EMPRECORD IS RECORD
	(
		FNAME EMPLOYEES.FIRST_NAME%TYPE,
		LNAME EMPLOYEES.LAST_NAME%TYPE,
		DPTNO EMPLOYEES.DEPARTMENT_ID%TYPE,
		DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE
	);
	REC EMPRECORD;
BEGIN
	ENO := &EMPLOYEE_ID;
	SELECT FIRST_NAME,LAST_NAME,EMPLOYEES.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_NAME INTO REC FROM EMPLOYEES, DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND EMPLOYEE_ID = ENO;
	DBMS_OUTPUT.PUT_LINE('FIRST NAME :' || REC.FNAME);
	DBMS_OUTPUT.PUT_LINE('LAST NAME :' || REC.LNAME);
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME :' || REC.DNAME);
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID :' || REC.DPTNO);

END;
/
