CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
    BOSS  EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT FIRST_NAME INTO BOSS FROM EMPLOYEES WHERE EMPLOYEE_ID =(SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = ECODE);

    DBMS_OUTPUT.PUT_LINE('IMMEDIATE BOSS : ' || BOSS);
END;
/
    
