CLEAR SCREEN
SET SERVEROUTPUT ON 
DECLARE
    CLERKS NUMBER (3);
    MANAGERS NUMBER (3);
BEGIN
    

    
 SELECT COUNT(*) INTO CLERKS FROM EMPLOYEES WHERE JOB_ID = ANY(SELECT JOB_ID FROM JOBS WHERE JOB_TITLE  LIKE '%Clerk');
SELECT COUNT(*) INTO MANAGERS FROM EMPLOYEES WHERE JOB_ID = ANY(SELECT JOB_ID FROM JOBS WHERE JOB_TITLE  LIKE '%Manager');




    DBMS_OUTPUT.PUT_LINE('TOTAL COUNT : ' || (CLERKS + MANAGERS));
END;
/