CLEAR SCREEN
SET SERVEROUTPUT ON
DECLARE
	A NUMBER := 20;
	B NUMBER := 10;

BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
	DBMS_OUTPUT.PUT_LINE(A);
	DBMS_OUTPUT.PUT_LINE(A+B);
	DBMS_OUTPUT.PUT_LINE('SUM OF '||A|| ' AND ' ||B||' = '||(A+B));
	DBMS_OUTPUT.PUT_LINE();
END;
/
