CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    V_DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE := '&DEPARTMENT_NAME';

    CURSOR EMPCURSOR IS 
        SELECT E.FIRST_NAME, E.JOB_ID, E.SALARY
        FROM EMPLOYEES E, DEPARTMENTS D
        WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
        AND D.DEPARTMENT_NAME = V_DEPT_NAME
        ORDER BY E.JOB_ID;

    TYPE EMPRECORD IS RECORD 
    ( 
        FNAME EMPLOYEES.FIRST_NAME%TYPE,
        JOB   EMPLOYEES.JOB_ID%TYPE,
        SAL   EMPLOYEES.SALARY%TYPE
    );

    REC EMPRECORD;

    JOBTOTSAL NUMBER := 0;
    JOBHEAD NUMBER := 0;
    GRANDTOTSAL NUMBER := 0;

    PREVJOB EMPLOYEES.JOB_ID%TYPE;

BEGIN
    OPEN EMPCURSOR;
    FETCH EMPCURSOR INTO REC;
    PREVJOB := REC.JOB;

    DBMS_OUTPUT.PUT_LINE('NAME      | JOB ID    | SALARY');

    WHILE EMPCURSOR%FOUND LOOP

        DBMS_OUTPUT.PUT_LINE(RPAD(REC.FNAME,10)||'|'||RPAD(REC.JOB,10)||'|'||LPAD(REC.SAL,6));

        JOBTOTSAL := JOBTOTSAL + REC.SAL;
        GRANDTOTSAL := GRANDTOTSAL + REC.SAL;
        JOBHEAD := JOBHEAD + 1;

        FETCH EMPCURSOR INTO REC;

        IF PREVJOB <> REC.JOB THEN
            DBMS_OUTPUT.PUT_LINE('------------------------------');
            DBMS_OUTPUT.PUT_LINE('SALARY FOR '||JOBHEAD||' HEADS: '||JOBTOTSAL);
            DBMS_OUTPUT.PUT_LINE('------------------------------');
            JOBTOTSAL := 0;
            JOBHEAD := 0;
        END IF;

        PREVJOB := REC.JOB;

    END LOOP;

    DBMS_OUTPUT.PUT_LINE('------------------------------');
    DBMS_OUTPUT.PUT_LINE('SALARY FOR '||JOBHEAD||' HEADS: '||JOBTOTSAL);
    DBMS_OUTPUT.PUT_LINE('------------------------------');
    DBMS_OUTPUT.PUT_LINE('GRAND TOTAL SALARY : '||GRANDTOTSAL);

END;
/