CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE EMPLOYEES.EMPLOYEE_ID%TYPE;
    YR    NUMBER;
BEGIN
    ECODE := &EMPLOYEE_ID;

    SELECT EXTRACT(YEAR FROM HIRE_DATE)
    INTO YR
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ECODE;

    IF YR = 1997 THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE WAS HIRED IN 1997');
    ELSE
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE WAS NOT HIRED IN 1997');
    END IF;
END;
/
