CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE
    ECODE   EMPLOYEES.EMPLOYEE_ID%TYPE;
    ESAL    EMPLOYEES.SALARY%TYPE;
    MAXSAL  SAL_GRADE.HISAL%TYPE;
BEGIN
    ECODE := &EMPLOYEE_ID;

    
    SELECT SALARY
    INTO ESAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ECODE;

    
    SELECT HISAL
    INTO MAXSAL
    FROM SAL_GRADE
    WHERE ESAL BETWEEN LOSAL AND HISAL;

    
    IF ESAL < MAXSAL THEN
        UPDATE EMPLOYEES
        SET SALARY = MAXSAL
        WHERE EMPLOYEE_ID = ECODE;

        DBMS_OUTPUT.PUT_LINE('SALARY INCREASED SUCCESSFULLY');
        DBMS_OUTPUT.PUT_LINE('OLD SALARY : ' || ESAL);
        DBMS_OUTPUT.PUT_LINE('NEW SALARY : ' || MAXSAL);
    ELSE
        DBMS_OUTPUT.PUT_LINE('SALARY IS ALREADY AT MAXIMUM OF THE GRADE');
        DBMS_OUTPUT.PUT_LINE('CURRENT SALARY : ' || ESAL);
    END IF;

END;
/
