CLEAR SCREEN
SET SERVEROUTPUT ON

DECLARE 
    ECODE   EMPLOYEES.EMPLOYEE_ID%TYPE;
    FNAME   EMPLOYEES.FIRST_NAME%TYPE;
    SAL     EMPLOYEES.SALARY%TYPE;
    I_SAL EMPLOYEES.SALARY%TYPE;
    D_SAL EMPLOYEES.SALARY%TYPE;
    YR      NUMBER;
BEGIN 
    ECODE := &EMPLOYEE_ID;

    SELECT FIRST_NAME,
           SALARY,
           SALARY*1.10,
           SALARY*0.95,
           EXTRACT(YEAR FROM HIRE_DATE)
    INTO   FNAME,
           SAL,
           I_SAL,
           D_SAL,
           YR
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ECODE;

    DBMS_OUTPUT.PUT_LINE('FIRST NAME : ' || FNAME);
    DBMS_OUTPUT.PUT_LINE('PRESENT SALARY : ' || SAL);
    DBMS_OUTPUT.PUT_LINE('10% INCREASED SALARY : ' || I_SAL);
    DBMS_OUTPUT.PUT_LINE('5% DECREASED SALARY : ' || D_SAL);
    DBMS_OUTPUT.PUT_LINE('YEAR OF HIRING : ' || YR);
END;
/

